### ISSUE TITLE
Selectors '> tag', '+ tag', and '~ tag'

### ISSUE THREAD

**Issue by unreal666** [facelessuser/soupsieve#110]
'>+~' symbols at the beginning of the selectors.
These selectors worked in Beautiful Soup 4.6.x.
But in 4.7.x there is no support for such selectors.

For example, the code below causes an soupsieve.util.SelectorSyntaxError exception.

    from bs4 import BeautifulSoup
    BeautifulSoup('<a>test<b>test2</b></a>').a.select('> b')

Result:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "D:\Programs\Programming\Python-3\lib\site-packages\bs4\element.py", line 1376, in select
        return soupsieve.select(selector, self, namespaces, limit, **kwargs)
      File "D:\Programs\Programming\Python-3\lib\site-packages\soupsieve\__init__.py", line 112, in select
        return compile(select, namespaces, flags, **kwargs).select(tag, limit)
      File "D:\Programs\Programming\Python-3\lib\site-packages\soupsieve\__init__.py", line 63, in compile
        return cp._cached_css_compile(pattern, namespaces, custom, flags)
      File "D:\Programs\Programming\Python-3\lib\site-packages\soupsieve\css_parser.py", line 205, in _cached_css_compile
        CSSParser(pattern, custom=custom_selectors, flags=flags).process_selectors(),
      File "D:\Programs\Programming\Python-3\lib\site-packages\soupsieve\css_parser.py", line 1010, in process_selectors
        return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
      File "D:\Programs\Programming\Python-3\lib\site-packages\soupsieve\css_parser.py", line 888, in parse_selectors
        sel, m, has_selector, selectors, relations, is_pseudo, index
      File "D:\Programs\Programming\Python-3\lib\site-packages\soupsieve\css_parser.py", line 713, in parse_combinator
        index
    soupsieve.util.SelectorSyntaxError: The combinator '>' at postion 0, must have a selector before it
      line 1:
    > b
    ^

**Comment by facelessuser** [comment]
You may first want to read https://facelessuser.github.io/soupsieve/#beautiful-soup-differences, but in short the old select did not follow the CSS specification, and though you may have been used to that behavior, it was not valid CSS.  CSS level 4 provides a solution though in the `:scope` selector, which Soup Sieve supports. Check out the link above to learn more.

**Comment by unreal666** [comment]
Hmm. I didn't notice it in the documentation.
Maybe, you need to add another difference in "Beautiful Soup Differences" doc section: order of nodes in result list:

    from bs4 import BeautifulSoup
    BeautifulSoup('<body><article>test</article></body>').select('article, body')

Old select: [article, body]
New select: [body, article] (as in CSS specification).

Can you add support for this order as in the old select (as keyword argument in select/select_one)?

**Comment by facelessuser** [comment]
> Maybe, you need to add another difference in "Beautiful Soup Differences" doc section: order of nodes in result list:

Yes, we can add that. This was brought to my attention somewhat recently as well.

> Can you add support for this order as in the old select (as keyword argument in select/select_one)?

Soup Sieve returns the nodes in the order they are found in the document as that is how the algorithm worked.  This is because we return the nodes as we find them, we don't keep a stack of nodes and then order them. It is simply as we find them when crawling the tree. We simply crawl the nodes and match each node. This is actually exactly how `querySelectorAll` works in browsers. To do it the old way, we would actually make the algorithm more inefficient, and it would require us to make major changes.

For these reasons, I cannot add support for the old ordering scheme.  I feel the way things are done now is more intuitive and more efficient for the current algorithm.

FWIW, I find the newer ordering more sane, but these types of things are subjective.

**Comment by facelessuser** [comment]
Documentation of the change in ordering has been added via PR #114 .

**Comment by facelessuser** [comment]
Closes this issue as the related question(s) have been answered, and where applicable, have been addressed.

**Comment by unreal666** [comment]
>> BeautifulSoup('<a>aaa</a><b>bbb</b>').a.select(':scope + *')
    []

Why?

**Comment by facelessuser** [comment]
Because that is how browsers work as well: https://codepen.io/facelessuser/pen/NoQGWY.

Select will not select the scope (the element that select is applied to) or elements that are not children of the scope.

**Comment by facelessuser** [comment]
I'll elaborate a little bit. Select matches each child against the selector. It's basically like doing this:

```python
import soupsieve as sv

for el in soup.a.children:
    sv.match(':scope + *', el)
```

**Comment by facelessuser** [comment]
Sorry that is a bad example above, it's kind of difficult to set a scope in a match as the element being matched is the scope.

You can see the implementation here though: https://github.com/facelessuser/soupsieve/blob/master/soupsieve/css_match.py#L1189

This is basically how browsers do it to, which is why they also do not match your example.

**Comment by unreal666** [comment]
Hmmm.

Due to the inability to use '+~' at the beginning selectors, I had to patch `Tag` class in my code. Often the code was taken from BS 4.6.3.  Maybe for someone it will be useful:

    import re, random, math

    import bs4
    from bs4 import Tag

    def version(v):
        return tuple(point.zfill(8) for point in v.split("."))

    if version(bs4.__version__) >= version('4.7'):
        def select_one(self, selector, namespaces=None, old_order=True, **kwargs):
            """Perform a CSS selection operation on the current element."""
            value = self.select(selector, namespaces, 1, old_order, **kwargs)
            return value[0] if value else None

        def select(self, selector, namespaces=None, limit=None, old_order=True, **kwargs):
            # Handle grouping selectors if ',' exists, ie: p,a
            if ',' in selector and old_order:
                if '"' not in selector and '\'' not in selector:
                    selectors = [x.strip() for x in selector.split(",")]
                else:
                    char = re.search('["\']', selector)[0]  # We consider the first quote character as the main one
                    if math.fmod(selector.count(char) , 2) != 0:
                        raise ValueError('Expected an even number of quotes, but received an odd')

                    selectors = []
                    is_prev_even = True  # A flag indicating the parity of the previous element in 'selectors' var.
                    for x in selector.split(","):
                        if is_prev_even:
                            selectors.append(x)
                        else:
                            selectors[-1] += ',' + x
                        is_prev_even = math.fmod(selectors[-1].count(char) , 2) == 0
                    selectors = [x.strip() for x in selector]

                context = []

                # If a selector is mentioned multiple times we don't want
                # to use it more than once.
                used_selectors = set()

                # We also don't want to select the same element more than once,
                # if it's matched by multiple selectors.
                selected_object_ids = set()
                for partial_selector in selectors:
                    if partial_selector == '':
                        raise ValueError('Invalid group selection syntax: %s' % selector)
                    if partial_selector in used_selectors:
                        continue
                    used_selectors.add(partial_selector)
                    candidates = self._select(partial_selector, namespaces=namespaces, limit=limit, **kwargs)
                    for candidate in candidates:
                        # This lets us distinguish between distinct tags that
                        # represent the same markup.
                        object_id = id(candidate)
                        if object_id not in selected_object_ids:
                            context.append(candidate)
                            selected_object_ids.add(object_id)
                    if limit and len(context) >= limit:
                        break
                return context

            return self._select(selector, namespaces=namespaces, limit=limit, **kwargs)

        def _select(self, selector, namespaces=None, limit=None, **kwargs):
            selector = selector.strip()
            first_char = selector[:1]

            if first_char == '>':
                selector = ':scope ' + selector
            elif first_char in '+~' and self.parent:
                    unique_attr = 'data-%s' % random.randrange(1000000,9999999)
                    self[unique_attr] = ''

                    elems = self.parent.new_select(
                        ':scope > [%s] %s' % (unique_attr, selector),
                        namespaces=None, limit=None, **kwargs)
                    del self[unique_attr]

                    return elems

            return self.new_select(selector, namespaces=namespaces, limit=limit, **kwargs)

        Tag.new_select_one = Tag.select_one
        Tag.new_select = Tag.select
        Tag.select_one = select_one
        Tag.select = select
        Tag._select = _select

**Comment by facelessuser** [comment]
Or, you could have called select on the parent before the `a` . Patching the library is unnecessary. There are enough selectors to get what you want without trying to mimic selectors that have never existed in CSS. If you provide a full example of what you are trying to target, I could even show you how to target what you are looking for.

**Comment by facelessuser** [comment]
FYI, the patched code posted above is extremely fragile, and I gauruntee it will break for anything complex. The splitting on `,` is how the old implementation used to do things and was one of the reasons the old select method broke so easily (there are many more reasons as well).

Take a selector like `p, div[attr="some, value"]`.  It easily breaks:

```py
>>> 'p, div[attr="some, value"]'.split(',')
['p', ' div[attr="some', ' value"]']
```

Above, we clearly split it in a way that makes no sense.

There are probably more issues in the above code, but  I am not going to evaluate it any further.

There is a reason why Soup Sieve exists and is now able to handle so many CSS selectors properly now while the old implementation could not. You are free to mimic the old way if you wish by patching the library, or I am open to showing you how you can utilize proper CSS selectors to accomplish what you'd like.

**Comment by unreal666** [comment]
> Or, you could have called select on the parent before the `a` . Patching the library is unnecessary.

It will not be the same result. Similar to me and so implemented (use generated random unique attribute):

```py3
                elems = self.parent.new_select(
                    # ':scope > [%s] %s' % (unique_attr, selector),
                    '[%s] %s' % (unique_attr, selector),
                    namespaces=None, limit=None, **kwargs)
```
> FYI, the patched code posted above is extremely fragile, and I gauruntee it will break for anything complex. The splitting on `,` is how the old implementation used to do things and was one of the reasons the old select method broke so easily (there are many more reasons as well).

I wrote that the old code is slightly **modified**. If there is `,` in the selector, then the code will be executed:

```py3
                # We consider the first quote character as the main one
                char = re.search('["\']', selector)[0]
                if math.fmod(selector.count(char), 2) != 0:
                    raise ValueError('Expected an even number of quotes, but received an odd')

                selectors = []
                # A flag indicating the parity of the previous element in 'selectors' var.
                is_prev_even = True
                for x in selector.split(","):
                    if is_prev_even:
                        selectors.append(x)
                    else:
                        selectors[-1] += ',' + x
                    is_prev_even = math.fmod(selectors[-1].count(char), 2) == 0
                selectors = [x.strip() for x in selectors]
```

The main thing is that one of the types of quotes is used only for `[atrr = "val1 val2"]`.

> There is a reason why Soup Sieve exists and is now able to handle so many CSS selectors properly now while the old implementation could not. You are free to mimic the old way if you wish by patching the library, or I am open to showing you how you can utilize proper CSS selectors to accomplish what you'd like.

And my implementation of selectors is not old. My **default** differences from new implementation:

* Old order of selectors. Useful when you need to specify the priority of selectors. This order is more important to me. I can, of course, do this: `tag.select('sel1') or tag.select('sel2') or tag.select('sel3') ...`. But this is a perversion.
* Transparent support of the characters ">+~" at the beginning of the selector. Browsers do not support this, most likely, due to reduced search performance.
* The final search itself is still done with the help of new selectors.

It is better to let me, as a user, have a choice: old selectors (but with improvements) with old order, old selectors with new order, and new selectors with new order.

**Comment by facelessuser** [comment]
> It will not be the same result. Similar to me and so implemented (use generated random unique attribute):

The selector you would use would be different, but you can achieve the same end result. That was my point, not that `+ selector` from a parent would work the same, but that you don't **need** to use `+ selector`. 

> And my implementation of selectors is not old. My **default** differences from new implementation:

I didn't look to closely, but I saw the splitting on `,` which was reminiscent of the old version, new or not. There will most likely be unexpected issues with this approach which is my my point, but if it works for you that is fine, but I want to make things clear for anyone coming in the future that they are likely to run into issues. This will mostly likely break complex selectors due to the way it is attempting to handle things (maybe I'm wrong, but there are no tests currently to substantiate this).

Whether this is acceptable to you or anyone else is none of my concern, but I will provide a full disclosure that this approach is not endorsed by the Soup Sieve project and is not recommended. I'm very much against monkey patching a library like Beautiful Soup this way, but again, I'm not here to change anyone's mind, simply to state the Soup Sieve project's stance, and that no support will be offered debugging issues that may arise with this approach.

> Transparent support of the characters ">+~" at the beginning of the selector. Browsers do not support this, most likely, due to reduced search performance.

They added `:scope`, so it is not necessarily due to performance.  There is no performance issue with `:scope > child`, which is equivalent to `> child`.  But when targeting a specific element with a query such as `target.querySelectorAll(":scope + sibling")` it is probably partly due to performance, but also due to algorithmic design.  Mostly likely, just like Soup Sieve, browsers implement `querySelectorAll` off the back of `matches`. This prevents duplicate logic. And by definition `querySelectorAll` is meant to return all the elements of the target (`target.querySelectorAll`), and siblings of the target do not belong to the target; therefore, they should not be matched.

> It is better to let me, as a user, have a choice: old selectors (but with improvements) with old order, old selectors with new order, and new selectors with new order.

Again, anyone can do anything they feel with this library.  While I offer support to ensure that Soup Sieve behaves as close to real CSS selectors as possible, I will not be able to offer help in monkey patched scenarios like this if things go awry.

---

The old select implementation suffered greatly from issues where it could not have multiple attributes or ids, `:nth-child` was implemented completely wrong, and it was extremely difficult to extend the support for more complex selectors. It was also difficult to debug. Some quirks existed, some that people found useful, but Soup Sieve aimed to give as close to a modern CSS implementation as was possible, and follows the CSS spec closely so that it won't have conflicts with future CSS support. That is the vision of Soup Sieve, and that will not change.

The author of Beautiful Soup did not write the old select method as it was contributed code, and was not interested in supporting the old select method due to how difficult it was to maintain. Issues with it persisted without solutions. The community was also not addressing the issues because it was difficult to debug, and not implemented in a way that could really be fixed without a major rewrite. Soup Sieve was created to fix this.

Unfortunately there were some quirks of BeautifulSoup that some people relied on in the past, but overall, I feel there is a tremendous net positive in feature, support, and even the ability to debug CSS related issues, despite the perceived loss of some of the quirks.
