### ISSUE TITLE
Get CSS selector

### ISSUE THREAD

**Issue by ShurayukiHime** [facelessuser/soupsieve#188]
Hi,
I am not sure if this falls within the scope of the project, but is it possible to actually *get* CSS selectors?

As far as I understand, you can `select()` or `select_one()` but this implies that you already know which parameter (CSS selector) to specify in there. On the other hand, in my case, I am looking for a (as much as possible) unique tag identifier that I can reuse in multiple iterations across an HTML page -- and I do not know it before. This is why I would like to extract the selector of a single tag that I found, e.g. while processing the HTML with Beautiful Soup.

Thank you.

**Comment by facelessuser** [comment]
@ShurayukiHime I'm afraid this is out of scope. Unfortunately finding what you don't know you want to find is kind of a vague requirement. How unique of a selector should you try to construct? Do you include classes and ids, do you identify nth-child positions, do you try and identify of possible pseudo classes? How much processing time are you willing to spend on this endeavor? There are a lot of questions that people may interpret differently.

On top of all of that, SoupSieve tries to generally give people what they are familiar with in browsers. And while SoupSieve may in some cases take some liberties at times, and also in other cases may be limited due to not operating in a browser, we generally try to be somewhat close to what browsers offer according to the CSS spec.

What I would recommend is that you create something that fits your current use case. I think at the very least, you could calculate `:nth-child`  index under a parent, and then walk the parents back to root. Maybe you could also include classes and ids, but I probably wouldn't do much more than that. You could create a function that takes an element and simply returns:

```
html > body:nth-child(1) > div:nth-child(2) > p:nth-child(1) > span:nth-child(3)
```

As far as SoupSieve is concerned, we will probably not be offering this feature.

@gir-bot remove S: triage
@gir-bot add T: feature, S: wontfix

**Comment by ShurayukiHime** [comment]
I see. Thanks a lot for your reply and insight!
