### ISSUE TITLE
Text and attribute pseudo-selectors

### ISSUE THREAD

**Issue by mscavnicky** [facelessuser/soupsieve#198]
Pre W3C, CSS Selectors only select nodes within XML documents, however they do not select text nodes or attribute values. Frameworks like `parsel` (scrapy) have successfully implemented pseudo-selectors like `::text` or `::attr` which allow you to do that. 

Given `soupsieve`'s current architecture, is it possible to add such selectors?

For reference https://parsel.readthedocs.io/en/latest/usage.html#extensions-to-css-selectors

**Comment by facelessuser** [comment]
Currently, I have intentionally not implemented any pseudo elements, just pseudo classes. Beautiful soup can access such on the returned element.

> Given `soupsieve`'s current architecture, is it possible to add such selectors?

It is most likely possible, but I would need to decide whether that is a path that I want to go down.
If I did go down this path, I would probably support no more than `::text` and maybe `::attr`.

This would of course add a bit more complexity as pseudo elements can't be processed in certain cases etc.

I won't say no, but I'll leave it as a maybe. If I do this, it may have to wait until I have the time to spend as this would be a fairly big addition.

@gir-bot remove S: triage
@gir-bot add T: feature, P: maybe

**Comment by facelessuser** [comment]
Looking at this. I think I need to first make sure I clearly understand the relationship of pseudo-elements with pseudo-classes etc.

Can pseudo-elements be used in *any* pseudo-classes? `is()` etc.

Once we have a clear understanding, it'll be easier to scope the work.

**Comment by facelessuser** [comment]
If we do this, it seems like we can exclude `::pseudo-elements` from any thing like `:is()` and `:not()`. It seems like it would be safe if they are always ensured to be the last selector. But obviously, we can have them in a selector list: `div::text, span::text`.

I think adding them into the selector parser is probably not going to be too bad.

The matcher though, I'll have to double check logic that filters out tags from other stuff and figure out how we get it through. It may not be that difficult. I imagine almost everything in the pipeline can filter to only tags, then we just extract pseudo-element content right at the end.

---

What I am uncertain of is how much content `::text` extracts. Here I would expect it to extract "text".

```
<span>text</span>
```

But given this scenario, would it extract everything? Only the nodes directly under the targeted element?

```
<p>This is some <strong>text</strong> in a paragraph</p>
```

I assume if we targeted `p` it would extract all descendant text nodes, is this assumption correct @mscavnicky?

**Comment by facelessuser** [comment]
So far, proof of concept shows this is possible:

```py
>>> from bs4 import _soup
>>> _soup('<span>test</span>').select_one('span::text')
'test'
```

But I have some concerns. One, our `select` and `select_one` are built on top of our `match`. Match takes an element and matches it against a selector. This all matches JavaScript's `querySelect` and `matches` which also take elements, not pseudo-elements, because you can really even provide a pseudo-element because they are quite arbitrary things.

In addition, it introduces inefficiencies as well. Not in the simple case above, but consider this:

```css
span, span::text
```

Normally, we can walk the selectors, and as soon as we find a match, we return true for our match, if called from select, we return the element under evaluation.

Now we have a case where a single element could match multiple selectors and require returning something different for each one. We can no longer shortcut the match, and *must* match against every selector in the selector list. In fact, we need to provide a whole new interface that instead of yielding true or false, must yield the element, text, and attributes for a selector list.

While I can see that this may be convenient, it really isn't super inconvenient just to call text on the element:

```py
_soup('<p>This is some <strong>text</strong> in a paragraph</p>').select_one('p').text
```

I'm questioning if the minor convenience is worth the added complexity and inefficiency. Remember, even JavaScript doesn't allow pseudo elements in their select functions as it doesn't quite make sense and you can extract the text with not too much effort.

**Comment by facelessuser** [comment]
While it is certainly possible to implement this. I think I'm going to pass. It adds unnecessary complexity and inefficiency for very little gain. I'm yet to hear how this is more helpful than just calling `text` on the returned elements.

While I'm open to a conversation on this, as things stand now, there are no plans to implement these.

@gir-bot remove P: maybe
@gir-bot add S: wontfix
