### ISSUE TITLE
CSS selector doesn't work despite working in Chrome

### ISSUE THREAD

**Issue by Almenon** [facelessuser/soupsieve#199]
The css selector "tbody > tr > td:nth-child(3) > span > a" does not work.

Reproducible example: https://repl.it/@almenon/ComplicatedGrotesqueIntegers
Note that it also fails w/ soupsieve==2.0.1

**Comment by facelessuser** [comment]
I appreciate the example, but can you provide a minimal example? Most likely it is due to the parser not quite translating things correctly; therefore, it won't find things as the content will be different than expected. For instance, I'd try with lxml vs html.parser. Do you consistently have this issue then?

A minimal example will easily show if there is a logical issue and will be easy to quickly debug.

**Comment by facelessuser** [comment]
Okay, I think I know what your issue is. It is as I described, a parser issue. If you search the file you provided, there is no `tbody` in the file.  Chrome will "normalize" some things in an HTML document when it loads it, so what you see in the inspector in Chrome isn't always what the source looks like. So, using `querySelector` in a browser may give you one result as it is parser a slightly different document than what BeautifulSoup is.

Now, when you use `html5lib` instead of `html.parser`, it finds both, because `html5lib` parsers documents more like browsers, so it injects `tbody` tags into the final content even though they do not exist in the source.

So, I would either use `html5lib` or adjust your selectors to parse what is in the source.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by Almenon** [comment]
Thanks! If `html5lib` behaves more like browsers, should that be the suggested parser in the [bs4 docs](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)?

**Comment by facelessuser** [comment]
🤷 They each have their pluses and minuses. I'd use what works for you in the situation you are in. `html5lib` I don't think is as fast as `html.parser`. `lxml` lib is faster than `html.parser` and is good for XML when using `lxml-xml`. Anyways, I'd just use what works for you.
