### ISSUE TITLE
CDATA handling in HTML changed in lxml parser with libxml2 2.9.12

### ISSUE THREAD

**Issue by mgorny** [facelessuser/soupsieve#220]
After upgrading the system libxml2 to 2.9.12 (or 2.9.11; 2.9.10 is the previous working version I have here), the two following tests fail with lxml built against the system library:

```
FAILED tests/test_extra/test_soup_contains.py::TestSoupContains::test_contains_cdata_html - AssertionError: Lists differ: ['1', '2'] != ['1']
FAILED tests/test_extra/test_soup_contains_own.py::TestSoupContainsOwn::test_contains_own_cdata_html - AssertionError: Lists differ: ['1', '2']...
```

The cause seems to be a different representation of CDATA:

```
        soup       = <html><body><div id="1">Testing that <span id="2">&lt;![CDATA[that]]&gt;</span>contains works.</div></body>
</html>
```

(i.e. `&lt![CDATA[...` instead of `<!--[CDATA[...`)

Note that in order to reproduce you need to both upgrade libxml2 and build lxml against the new version. Binary wheels are statically linked to an old version of libxml2, so they do not reproduce the issue yet. For example, I have been able to reproduce it with tox after swapping the installed lxml version:
```
. .tox/py39/bin/activate
pip uninstall lxml
pip install lxml --no-binary lxml
```

I am also not sure whether this isn't a bug in libxml2 or lxml.

**Comment by facelessuser** [comment]
Hmm. I would first check if this is expected behavior in lxml first. I'm not sure how this change looks in pure lxml and if they are even handling things correctly. Can you test pure lxml, and see if it returns proper results?

If this is expected lxml behavior, I will then have to check if BeautifulSoup should be handling this differently.

Only if both of the above libraries are handling things as expected, will I then have to investigate what needs to change in Soup Sieve.

@gir-bot add S: more-info-needed

**Comment by facelessuser** [comment]
This should clarify that lxml probably doesn't work with libxml > 2.9.10 yet: https://github.com/lxml/lxml/commit/450487092251816b4252a0e8694bf50abb1d4046.

From what I can gather, it seems you probably shouldn't build lxml against anything greater than 2.9.10 currently. I would take any questions to them as this does not appear to be a Soup Sieve issue.

**Comment by mgorny** [comment]
Sure but I don't really know what this code/test is doing, so if I'm supposed to go upstream, I'd appreciate some suggestion on what to look for. Ideally, some constrained lxml (or bs4?) example of code that actually makes this happen. I'm sorry but I have hundreds of packages on my plate and can't go figuring every single one out.

That said, I did restrict libxml2 version for us. Still, this will eventually need to be solved. What I can tell is that no tests in bs4 or lxml fail with the new libxml2 version, so if this bug affects them, they don't test for it.

**Comment by facelessuser** [comment]
As I linked above, it seems lxml specifically doesn't use those versions with the vague mention that they are incompatible.  I'm not sure why, but it seems to indicate that there are some things that don't work proper, so I wouldn't spend more time on this.

**Comment by facelessuser** [comment]
Just to make sure, let me look over the failing tests just to determine what this difference implies.

**Comment by facelessuser** [comment]
Here is the implications. This is how previous versions of lxml parse CDATA through BeautifulSoup. Notice the difference of lxml parsing HTML vs lxml parsing XML.

```py
>>> soup = BeautifulSoup('<body><div id="1">Testing that <span id="2"><![CDATA[that]]></span>contains works.</div></body>', 'lxml')
>>> soup
<html><body><div id="1">Testing that <span id="2"></span>contains works.</div></body></html>
>>> soup = BeautifulSoup('<body><div id="1">Testing that <span id="2"><![CDATA[that]]></span>contains works.</div></body>', 'xml')
>>> soup
<?xml version="1.0" encoding="utf-8"?>
<body><div id="1">Testing that <span id="2">that</span>contains works.</div></body>
```

In HTML, the CDATA content is simply ignored and discarded, while in XML, the content within CDATA is parsed. The HTML behavior described above is exactly how modern HTML browsers handle CDATA. The recognize them, but they are not part of HTML and ignored. https://codepen.io/facelessuser/pen/vYxWemE.

This is what you are showing the new version of libxml2 causes lxml to render:

```html
<html><body><div id="1">Testing that <span id="2">&lt;![CDATA[that]]&gt;</span>contains works.</div></body>
</html>
```

It appears that lxml with the new version of libxml2 just treats them as raw text, escapes HTML entities and returns the content. This is not how browsers handle this at all.

I would argue that lxml is either handling some change in libxml2 wrong and is now displaying the CDATA content it should not, or libxml2 messed something up in CDATA handling.

---

Before I alter tests to handle this difference, which I could, I would need to known that lxml officiall supports libxml2 versions greater than 2.9.10. I would need to have confirmation that they also view this new behavior as intended.

As things stand now, this does not match browsers or past lxml behavior. I would expect this to be bug, and not only that, on their side, not ours.

**Comment by mgorny** [comment]
Thank you for the explanation. I suppose my next stop is BS4 then. Even if it's not their bug, I suppose adding a test for this would be helpful.

> As I linked above, it seems lxml specifically doesn't use those versions with the vague mention that they are incompatible. I'm not sure why, but it seems to indicate that there are some things that don't work proper, so I wouldn't spend more time on this.

I think the primary reason was [lxml#1928795](https://bugs.launchpad.net/lxml/+bug/1928795) (also reported to libxml2 as [libxml2#255](https://gitlab.gnome.org/GNOME/libxml2/-/issues/255)). Long story short, lxml was doing something wrong and when libxml2 changed internals the hell broke loose. However, libxml2 worked around that on their side and we've backported the patch. This is obviously not helpful to lxml upstream until they either fix their code or libxml2 makes yet another release.

From our perspective, libxml2 upgrade is somewhat of a big deal because the old version has a number of vulnerabilities (it's vulnerable to the whole lot of recent XML attacks). In either case, I suppose the situation sucks for lxml a lot more because they force a vulnerable library while we can patch it somehow.

**Comment by facelessuser** [comment]
Yeah, I can certainly "fix" our test. We can just analyze the returned content, and if it contains `&lt;![CDATA[`, we know we have a need to assert against the test finding two instances of our target instead of one, but I think the HTML result should not have the CDATA returned at all. That is the only reason I'm not "fixing" it right now. I think the tests would be incorrect and simply passing because we don't want them to fail. I'd rather have a proper passing test with real meaning behind it.

As things stand, we fail our test with the latest libxml2, but you can still use SoupSieve with it as long as you are aware of this difference and understand what the failing tests mean.

**Comment by facelessuser** [comment]
I guess they expose checking the libxml2 version, so we could ignore the test for `lxml` for specific versions of `libxml2` with a note as to why:

```py
>>> from lxml import etree
>>> etree.LIBXML_VERSION
(2, 9, 10)
```

I'm sure someone expecting certain CDATA behavior on all systems may find the difference in CDATA handling surprising though, so maybe just allowing the tests to fail with an open issue describing why we haven't "fixed" it may be sufficient for now.

**Comment by mgorny** [comment]
Don't worry, there's no hurry. Worst case, we can ignore these two tests. But I'm going to try to figure out what changed first.

**Comment by mgorny** [comment]
Heh, nothing like a good bisect:

```
173a0830dcec769a5f12c5c55ef4ab424b388efb is the first bad commit
commit 173a0830dcec769a5f12c5c55ef4ab424b388efb
Author: Nick Wellnhofer <wellnhofer@aevum.de>
Date:   Wed Jul 22 23:15:35 2020 +0200

    Fix quadratic runtime when push parsing HTML start tags
    
    Make sure that htmlParseStartTag doesn't terminate on characters for
    which IS_CHAR_CH is false like control chars.
    
    In htmlParseTryOrFinish, only switch to START_TAG if the next character
    starts a valid name. Otherwise, htmlParseStartTag might return without
    consuming all characters up to the final '>'.
    
    Found by OSS-Fuzz.

 HTMLparser.c | 40 +++++++++++++++++++++++++++++++---------
 1 file changed, 31 insertions(+), 9 deletions(-)
```

Now I just have to figure out if it's libxml2 bug or a change is necessary in lxml.

**Comment by mgorny** [comment]
Filed https://bugs.launchpad.net/beautifulsoup/+bug/1930164 now and I'm stopping making noise here ;-).

**Comment by facelessuser** [comment]
As this appears to be an upstream issue, and there is no actionable item for us here, closing for housekeeping. If in the future, there is some specific task for SoupSieve related to this, we can reopen or open a new issue.

**Comment by stefanor** [comment]
> From what I can gather, it seems you probably shouldn't build lxml against anything greater than 2.9.10 currently.

Whether or not that's true, Debian unstable now has an lxml built against 2.9.12, and so I'm patching these two tests to XFAIL on Debian (because their behaviour is now different across the parsers, with libxml2 >= 2.9.11).

**Comment by facelessuser** [comment]
Has anyone bothered to try and get a formal response from lxml? You'll create passing tests and ship a broken lxml.

**Comment by stefanor** [comment]
@mgorny reported this to lxml in https://bugs.launchpad.net/lxml/+bug/1930224, no reply yet. He also asked for help in reporting the bug to libxml2 upstream, in there.

The project maintainer replied in https://bugs.launchpad.net/lxml/+bug/1928795/comments/1 - several hours before committing https://github.com/lxml/lxml/commit/450487092251816b4252a0e8694bf50abb1d4046, so even though he didn't link to that bug, I assume that was what he was thinking of. (Reminder to the void: Please explain your reasons for making changes in commit messages.)

You can also follow that thread into https://gitlab.gnome.org/GNOME/libxml2/-/issues/255 leading to the patch resolving *that* particular issue in libxml2. In that thread libxml2 is clear that there will be no security support for libxml2 2.9.10, from upstream.

Distros have to pick our poison between following new releases and holding at an old version because of bugs. Outside of stable releases (where the whole world is pinned), pinning older versions can only ever be a short-term work-around. It often takes a lot of work to migrate to new versions of things, and we don't wait for everything to be 100% resolved before committing to it. This was not my call, here (I don't maintain lxml in Debian, nor was I aware of this issue before yesterday), but I support the change.

**Comment by facelessuser** [comment]
Well, I'm okay with a patch in tests to work around the failing test when libxml2 version is a faulty one. I will most likely also pin an issue, maybe this one, with an explanation that the issue is not with us.

**Comment by stefanor** [comment]
Finished that reproducer in C and filed https://gitlab.gnome.org/GNOME/libxml2/-/issues/312 with upstream libxml2.

**Comment by facelessuser** [comment]
Reopening this as this is now a real issue. With the release of lxml 4.7+, it is compiled against a later libxml2 version. It seems that CDATA in using lxml's HTML mode will not strip out CDATA.

**Comment by facelessuser** [comment]
We will basically split up the CDATA tests to per parser tests and check the `libxml2` version when determining what the results should be when evaluating CDATA with `lxml`.

**Comment by facelessuser** [comment]
Tests have been "fixed". It is certainly possible that `lxml` or `libxml2` will fix this as a regression and once again break our tests. If that happens, we will once again "fix" the tests.
