### ISSUE TITLE
Attribute Selector Case Sensitivity: Whitespace

### ISSUE THREAD

**Issue by orbisvicis** [facelessuser/soupsieve#262]
The CSS Level 4 specification doesn't explicitly require whitespace before the attribute selector's case-sensitivity identifier; simply that the identifier (`i|s`) must occur before the closing bracket [1]. The following example does not throw any errors in either Firefox or Chrome:

``` javascript
document.querySelector("a[attr='value'i]");
```

All the examples given by the specification incorporate whitespace. In the examples below (bare attributes or unquoted attribute values) a space is clearly required.

``` css
a[attr=value i]
a[attr i]
```

Do you think soupsieve should compile the following CSS selector, or throw an error?

``` python
sv.compile("a[attr='value'i]")
```

soupsieve: 2.4

[1] [CSS Level 4, Attribute Selectors, Case-sensitivity](https://www.w3.org/TR/selectors-4/#attribute-case)

**Comment by facelessuser** [comment]
Yeah, this burned me in my color library recently too: https://github.com/facelessuser/coloraide/issues/279. They mention it being a space-delimited syntax, but then I realized browsers were allowing nonsense like this: `color(srgb 1 0.5.4)`. I've since realized that they just parse the tokens and optionally allow spaces. Attributes syntax was written before I realized what space delimited syntax in CSS actually means.

Anyways, it is easy enough to fix:

```
>>> BS('<div attr="NaMe">Test</div>', 'html.parser').select('div[attr=name i]')
[<div attr="NaMe">Test</div>]
>>> BS('<div attr="NaMe">Test</div>', 'html.parser').select('div[attr=namei]')
[]
>>> BS('<div attr="NaMe">Test</div>', 'html.parser').select('div[attr="name"i]')
[<div attr="NaMe">Test</div>]
```
PR with fix here: https://github.com/facelessuser/soupsieve/pull/263
