### ISSUE TITLE
select_one and select

### ISSUE THREAD

**Issue by yjqiang** [facelessuser/soupsieve#45]
I like the function `soup.select()` and `soup.select_one()`. Maybe you can add `select_one` to this repo? If the result is None, I can easily know that there are no match objects. Just like https://docs.python.org/3/library/re.html#re.search  Infact, I don't know why you use `limit` to control the number of the results. I think people would need one or all of the results.

**Comment by facelessuser** [comment]
> And thanks for the css seletors you invented, like !=, that is what I need now.

Well, I didn't ivent it, it was something other libraries have been using for a while. I know JQuery and the lxml CSSSelect library implement it.  It seemed too logical and convenient not to add here as well.

> I like the precompile. It looks like the re module (re.compile).

Yeah, that was kind of my model when I wrote it.  Seemed like if you had a script with known things you were looking for, instead of calling `select` over and over, and reparsing the selector string and building the search object, it would be best to:

1. Allow you to build that thing once and reuse it.

2. Cache them in case you didn't think to precompile it to begin with.

Both of these the `re` module employs.

**Comment by yjqiang** [comment]
> 
> With all of that said, for completeness with the original Beautiful Soup API, I can see the desire to have the familiar `select_one()` as well with its convenience of not having to index into the the first in the list. This seems a reasonable request.
> 

So now I just need to sit down and wait for the new `select_one` api.

**Comment by facelessuser** [comment]
Had a little time this morning, so I implemented the feature via #46. It will be in the `1.5.0` release.  Not sure when that release is coming yet. Maybe not too far out. I imagine major releases will slow down moving forward as I feel the project has a solid feature base now, but I think I'll at least get this one out within the week.

**Comment by facelessuser** [comment]
FYI, I've released `1.5.0` as I found a bug in `nth` selectors while I was adding the `:dir()` selector. I wanted to get the fix out, so I went ahead and cut the `1.5.0` release.
