### ISSUE TITLE
XML default namespace leads to TypeError: __init__() keywords must be strings

### ISSUE THREAD

**Issue by mjpieters** [facelessuser/soupsieve#68]
This is a bug with handling valid XML namespaces; soupsieve assumes all namespaces have a prefix:

```xml
<prefix:tag xmlns:prefix="...">
```

but the prefix can be omitted to define a *default* namespace:

```xml
<tag xmlns="...">
```

meaning that any element without a `prefix:` prepended to the tag name is in that namespace. See [section 6.2 of the XML namespaces 1.1 spec](https://www.w3.org/TR/2006/REC-xml-names11-20060816/#defaulting).

During parsing, `lxml` passes in a default namespace under the `None` key, e.g. `{None: "..."}`, and unique keys are accumulated in the `soup._namespaces` dictionary. soupsieve assumes the dictionary only ever has string keys, so an XML document with a default namespace leads to an exception.

Test case (using BeautifulSoup 4.7 for convenience):

```python
>>> from bs4 import BeautifulSoup, __version__
>>> __version__
'4.7.0'
>>> sample = b'''\
... <?xml version="1.1"?>
... <!-- unprefixed element types are from "books" -->
... <book xmlns='urn:loc.gov:books'
...       xmlns:isbn='urn:ISBN:0-395-36341-6'>
...     <title>Cheaper by the Dozen</title>
...     <isbn:number>1568491379</isbn:number>
... </book>
... '''
>>> soup = BeautifulSoup(sample, 'xml')
>>> soup._namespaces
{'xml': 'http://www.w3.org/XML/1998/namespace', None: 'urn:loc.gov:books', 'isbn': 'urn:ISBN:0-395-36341-6'}
>>> soup.select_one('title')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mj/Development/venvs/stackoverflow-latest/lib/python3.7/site-packages/bs4/element.py", line 1345, in select_one
    value = self.select(selector, namespaces, 1, **kwargs)
  File "/Users/mj/Development/venvs/stackoverflow-latest/lib/python3.7/site-packages/bs4/element.py", line 1377, in select
    return soupsieve.select(selector, self, namespaces, limit, **kwargs)
  File "/Users/mj/Development/venvs/stackoverflow-latest/lib/python3.7/site-packages/soupsieve/__init__.py", line 108, in select
    return compile(select, namespaces, flags).select(tag, limit)
  File "/Users/mj/Development/venvs/stackoverflow-latest/lib/python3.7/site-packages/soupsieve/__init__.py", line 50, in compile
    namespaces = ct.Namespaces(**(namespaces))
TypeError: __init__() keywords must be strings
```

where `<title>Cheaper by the Dozen</title>` was expected.

**Comment by facelessuser** [comment]
I would prefer that this is fixed in BeautifulSoup as `None` has meaning internally in SoupSieve in regards to namespaces.

**Comment by mjpieters** [comment]
Check! I should have checked for that; I presumed it was a SoupSieve problem as this bug first showed up in 4.7.0.

It’s lxml that uses `None` as the key, by the way, which is a good choice if (invalid) empty prefixes were to be supported, but since they are not the lxml builder should just replace `None` with `''` when processing namespaces.

I’m on mobile now, I can try and move this over to the launchpad tracker some time later today or tomorrow.

**Comment by facelessuser** [comment]
Yeah, I was just looking at BeautitulSoup's code, and I see that it is just writing the `None` from lxml. From BeautifulSoup's side, it probably does make sense to store what lxml is providing.  I need to look at this more and see the best way to bridge the gap here.  Maybe, it will make sense to support `None` here. I just hadn't considered this approach as BeautifulSoup was never expected to give a default to SoupSieve, and then it was added.

**Comment by facelessuser** [comment]
@mjpieters, Thinking about this more, I will probably allow SoupSieve to parse a `None` as a key.  As far as BeautifulSoup is concerned, it makes sense for it to use `None` internally.

I'll relax the input to allow a `None` key, but it will be remapped for our use as `''`. If `None` is given, it will be assumed as `''`.  If both `None` and `''` is given (which BeautifulSoup should never do) then I will consider it a user error and raise an exception.

The name of the prefix doesn't really matter in the context of selecting except in attributes. You could technically use a prefix that doesn't match what is in the XML as long as the actual namespace matches. The same is true in the CSS specification. With attributes it is different because we are actually comparing the string value, that has to match, and `None` doesn't equal an empty string.

Thanks for reporting this!  I imagine little corner cases like this will crop up as the user has exploded by inclusion with BeautifulSoup. Though since selectors used to be so bad in BeautifulSoup, there are probably a lot of people who avoided using `select` and `select_one` 🙂 .

**Comment by facelessuser** [comment]
Just an FYI, I would probably mention that relying on BeautifulSoup's default namespace, could lead to issues when dealing with implicit namespaces. This is probably why CSS also doesn't provide defaults.

```xml
<?xml version="1.1"?>
<!-- unprefixed element types are from "books" -->
<library>
<book xmlns='urn:loc.gov:books'
       xmlns:isbn='urn:ISBN:0-400-40000-0'>
    <title>Cheaper by the Dozen</title>
    <isbn:number>1568491379</isbn:number>
</book>
<book xmlns='urn:loc.gov:books'
       xmlns:isbn='urn:ISBN:0-395-36341-6'>
    <title>Cheaper by the Dozen</title>
    <isbn:number>1568491379</isbn:number>
</book>
<library>
```

Beautiful soup will not store both in its dictionary because they would share the same key.  This is why I mentioned earlier that exact prefix name doesn't matter and is more a convenience for selecting.  The namespace matters.

```py
namespaces = {
    'xml': 'http://www.w3.org/XML/1998/namespace',
    '': 'urn:loc.gov.books',
    'isbn1': 'urn:ISBN:0-395-36341-6',
    'isbn2': 'urn:ISBN:0-400-40000-0'
}
```

**Comment by facelessuser** [comment]
Ah. Glad to see people trying to use it.  Sad it didn't just work. I have a working fix locally. I'll probably push a 1.7.0 release as this will technically change the API, but I do want to get a fix out so people aren't breaking in these kind of things.

**Comment by facelessuser** [comment]
So, my suggested change of not indexing non-prefixed namespaces has been merged (not released) in BeautifulSoup.  This would make the need to handle `None` here unnecessary. I'm not sure when BeautifulSoup is targeting the next bugfix release (hopefully soon).  If it does get released soon enough, we'll actually pass on accepting None and it should no longer occur.  I much prefer a consistent input for SoupSieve.

**Comment by facelessuser** [comment]
This has been fixed in BeautifulSoup 4.7.1. I don't have enough reputation so I can't comment on the SO question (that restriction is so dumb, I've often not been able to answer questions on SO on things I am the maintainer of).  This issue can be resolved by updating to the latest BeautifulSoup.

**Comment by mjpieters** [comment]
I'll update the post, thanks! The restrictions on commenting on SO are in place because spammers have ruined the internet for us. If a question requires commenting, it probably is not yet answerable, best to move on to those you can answer; you'll get the reputation quicker than blinking that way.

**Comment by facelessuser** [comment]
Thanks for the info!
